version: '2'
services:
  orderingapplication-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/orderingApplication/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=orderingApplication
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
